services:
  # MySQL
  spms-mysql:
    image: mysql:8.0
    container_name: spms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spms
      MYSQL_USER: spms
      MYSQL_PASSWORD: spms
    ports:
      - "13306:3306"
    volumes:
      - spms_mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - spms-network

  # Redis
  spms-redis:
    image: redis:alpine
    container_name: spms-redis
    restart: always
    ports:
      - "16379:6379"
    # 无需密码
    command: redis-server --requirepass ""
    volumes:
      - spms_redis_data:/data
    networks:
      - spms-network

  # Server
  spms-server:
    build:
      context: ./SPMS-Server
      dockerfile: Dockerfile
    container_name: spms-server
    restart: always
    depends_on:
      - spms-mysql
      - spms-redis
    volumes:
      - spms_server_data:/home/
    networks:
      - spms-network
  # Web
  spms-web:
    build:
      context: ./SPMS-Web
      dockerfile: Dockerfile
      args:
        - NODE_OPTIONS=--max-old-space-size=4096
    container_name: spms-web
    restart: always
    ports:
      - "18080:80"
    depends_on:
      - spms-server
    volumes:
      - spms_server_data:/home/
    networks:
      - spms-network
# Volumes
volumes:
  spms_mysql_data:
  spms_redis_data:
  spms_server_data:

    # Virtual Networks
networks:
  spms-network:
    driver: bridge